In [3]:
import numpy as np

"""<br>
@Author: Girish <br>
@Date: 2024-08-06 <br>
@Last Modified by: Girish <br>
@Last Modified time: 2024-08-06 <br>
@Title: Numpy Library Problems <br>
"""

1.Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.

In [4]:

def convert_list_to_array(mylist):
    
        
    """
    Converts a given list to a numpy array and prints it along with its type.
    
    Parameters:
        mylist (list): The list to be converted to a numpy array.
    
    Returns:
        None
    """
    

    converted_list = np.array(mylist)
    print(converted_list)
    print(type(converted_list))


def main():

    mylist = []
    for i in range(1, 11):
        mylist.append(i)
    print(mylist)
    print(type(mylist))
    convert_list_to_array(mylist)

if __name__ == "__main__":
    main()


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:

In [5]:


def create_and_reshape_2d_array(start, end, rows, cols):
    
    
    """
    Description: Creates a 1D numpy array of integers from start to end (exclusive) and reshapes it into a 2D array.
    
    Parameters:
        start (int): The starting value of the range.
        end (int): The ending value of the range (exclusive).
        rows (int): The number of rows in the 2D array.
        cols (int): The number of columns in the 2D array.
    
    Returns:
        np.ndarray: The created and reshaped 2D numpy array.
      
    """
     
    array_1d = np.arange(start, end)
    if len(array_1d) != rows * cols:
        raise ValueError("The number of elements does not match the specified shape.")
    return array_1d.reshape(rows, cols)

def main():

    start = int(input("Enter the start of the range: "))
    end = int(input("Enter the end of the range: "))
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    
    try:
        array_2d = create_and_reshape_2d_array(start, end, rows, cols)
        print("1D Array:")
        print(np.arange(start, end))
        print("Reshaped 2D Array:")
        print(array_2d)
    except ValueError as ve:
        print(ve)

if __name__ == "__main__":
    main()


The number of elements does not match the specified shape.


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.


In [32]:

def create_null_vector_and_update():
      
    """
    Description: Creates a null vector (1D array of zeros) of length 10 and updates the 7th element to 11.
    
    Parameters:
        None
    
    Returns:
        np.ndarray: The updated null vector with the 7th element set to 11.
    """
    
    
    null_vector = np.zeros(10)
    print("Initial null vector:")
    print(null_vector)
    null_vector[6] = 11
    print("Updated null vector with the 6th element set to 11:")
    print(null_vector)
    return null_vector


def main():

    create_null_vector_and_update()

if __name__ == "__main__":
    main()


Initial null vector:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated null vector with the 6th element set to 11:
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4.Write a Python program to reverse an array (first element becomes last).

In [7]:

def reverse_array(array):
    
    
    """
    Description: Reverses the given numpy array.
    
    Parameters:
        array (np.ndarray): The numpy array to be reversed.
    
    Returns:
        np.ndarray: The reversed numpy array.
    """
    
    
    reversed_array = np.array(list(array)[::-1])
    return reversed_array



def main():
    
    array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    reversed_array = reverse_array(array)
    print("Original array:", array)
    print("Reversed array:", reversed_array)

if __name__ == "__main__":
    main()


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Reversed array: [10  9  8  7  6  5  4  3  2  1]


Create a 2D Array with 1 on the Border and 0 Inside


In [8]:

def create_2d_border_array(rows, cols):
    """
    Description:  Creates a 2D list with 1 on the border and 0 inside.
    
    Parameters:
        rows (int): The number of rows in the array.
        cols (int): The number of columns in the array.
    
    Returns:
        list: The created 2D list with 1 on the border and 0 inside.
    """
    array = [[0 for index in range(cols)] for index in range(rows)]
    
    for i in range(rows):
        for j in range(cols):
            if i == 0 or i == rows - 1 or j == 0 or j == cols - 1:
                array[i][j] = 1
    
    return array

def main():

    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    
    border_array = create_2d_border_array(rows, cols)
    print("2D Array with 1 on the border and 0 inside:")
    for row in border_array:
        print(row)

if __name__ == "__main__":
    main()


2D Array with 1 on the border and 0 inside:
[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [9]:


def create_2d_border_array(rows, cols):
    """
    Description:  Creates a 2D list with 0 on the border and 1 inside.
    
    Parameters:
        rows (int): The number of rows in the array.
        cols (int): The number of columns in the array.
    
    Returns:
        list: The created 2D list with 0 on the border and 1 inside.
    """
 
    array = [[0 for index in range(cols)] for index in range(rows)]
    
    
    for i in range(1, rows - 1):
        for j in range(1, cols - 1):
            array[i][j] = 1
    
    return array

def main():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    
    border_array = create_2d_border_array(rows, cols)
    print("2D Array with 0 on the border and 1 inside:")
    for row in border_array:
        print(row)

if __name__ == "__main__":
    main()


2D Array with 0 on the border and 1 inside:
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 0, 0, 0, 0]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:


def check_board_creation(mylist):
    
    
    """
    Description:
        Converts a flat list to an 8x8 numpy array and prints it.
    
    Parameters:
        mylist (list): List of 64 elements to be reshaped into an 8x8 array.
    
    Returns:
        None
    """
    
    
    array = np.array(mylist)
    check_board = array.reshape(8, 8)
    print(check_board)



def main():
    
    mylist = []
    for i in range(8):
        row = [0, 1] * 4  
        if i % 2 == 1:  
            row = row[::-1]  
        mylist.extend(row)
    
    check_board_creation(mylist)

if __name__ == "__main__":
    main()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.


In [11]:

def tuple_to_array(mytuple):
    
    """
    Description :
        Converts Tuple to numpy array
        
    Prameter : 
        mytuple (tuple): Tuple to be converted
    
    Return :
        array : numpy array
        
    """
    
    return(np.array(mytuple))



def list_to_array(mylist):

    """
    Description :
        Converts Tuple to numpy array
        
    Prameter : 
        mylist (list): Tuple to be converted
    
    Return :
        array : 
            numpy array
        
    """
    
    return(np.array(mylist))


def main():
    
    mylist = [1,2,3,4,5,6,7,8,9,10]
    mytuple = (11,12,13,14,15,16,17,18,19)
    print(mylist)
    print(list_to_array(mylist))
    print(mytuple)
    print(tuple_to_array(mytuple))
    

if __name__ == "__main__":
    main()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
(11, 12, 13, 14, 15, 16, 17, 18, 19)
[11 12 13 14 15 16 17 18 19]


9. Write a Python program to append values to the end of an array

In [12]:


def append_to_array(array , elements):
    
    
    """
    Description :
        Appends elements to a NumPy array.

    Parameters:
        array (np.ndarray): The original NumPy array.
        elements (list or np.ndarray): The elements to append to the array.

    Returns:
        np.ndarray: A new NumPy array with the elements appended.
    """
    
    
    x = np.append(array, elements)
    print(x)


def main():
    original_array = [1, 2, 3, 4, 5]
    print("Original Array:", original_array)
    
    elements_to_append = [6,7,8,9,10]
    
    new_array = append_to_array(original_array, elements_to_append)
    
    print("New Array after appending:", new_array)


if __name__ == "__main__":
    main()


Original Array: [1, 2, 3, 4, 5]
[ 1  2  3  4  5  6  7  8  9 10]
New Array after appending: None


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [13]:

def process_complex_array(mylist):
    
    
    """
    Processes a list of complex numbers to extract their real and imaginary parts.

    Parameters:
        mylist (list): A list of complex numbers.

    Returns:
        tuple: A tuple containing two NumPy arrays:
            - The real parts of the complex numbers.
            - The imaginary parts of the complex numbers.
    """
    
    
    array = np.array(mylist)
    real_parts = np.real(array)
    imaginary_parts = np.imag(array)
    return real_parts, imaginary_parts

def main():

    mylist = [1.00000000 + 0.j, 0.70710678 + 0.70710678j]
    real_parts, imaginary_parts = process_complex_array(mylist)
    
    print("Real Parts:", real_parts)
    print("Imaginary Parts:", imaginary_parts)

if __name__ == "__main__":
    main()


Real Parts: [1.         0.70710678]
Imaginary Parts: [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [14]:


def array_statistics(arr):
    
    
    """
    Calculates the number of elements, length of one element in bytes, and total bytes consumed by the elements of a NumPy array.

    Parameters:
        arr (np.ndarray): The NumPy array to analyze.

    Returns:
        tuple: A tuple containing:
            - The number of elements in the array.
            - The length of one array element in bytes.
            - The total bytes consumed by the elements of the array.
    """
    
    
    num_elements = arr.size
    element_size = arr.itemsize
    total_size = arr.nbytes

    return num_elements, element_size, total_size



def main():

   
    array = np.array([1, 2, 3, 4, 5], dtype=np.int64)

  
    num_elements, element_size, total_size = array_statistics(array)
    
  
    print(f"Number of elements: {num_elements}")
    print(f"Length of one element in bytes: {element_size}")
    print(f"Total bytes consumed by the elements: {total_size}")

if __name__ == "__main__":
    main()


Number of elements: 5
Length of one element in bytes: 8
Total bytes consumed by the elements: 40


12. Write a Python program to find common values between two arrays."

In [15]:

def find_common_values(array1, array2):
    
    
    """
    Finds common values between two numpy arrays.

    Parameters:
        array1 (numpy.ndarray): The first array.
        array2 (numpy.ndarray): The second array.

    Returns:
        numpy.ndarray: An array containing the common values.
    """
    
    
    common_values = []
    for value in array1:
        if value in array2 and value not in common_values:
            common_values.append(value)
    return np.array(common_values)



def main():

    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])

    
    common_values = find_common_values(array1, array2)

    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print("Common values between two arrays:")
    print(common_values)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [16]:


def find_set_difference(array1, array2):
    
    
    """
    Finds the set difference of two numpy arrays using built-in functions.

    Parameters:
        array1 (numpy.ndarray): The first array.
        array2 (numpy.ndarray): The second array.

    Returns:
        numpy.ndarray: A sorted array containing the unique values in array1 that are not in array2.
    """
    
    
    difference = np.setdiff1d(array1, array2)
    return difference

def main():

    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])

    set_difference = find_set_difference(array1, array2)

    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print("Set difference of array1 and array2 (sorted, unique values in array1 not in array2):")
    print(set_difference)

if __name__ == "__main__":
    main()



Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Set difference of array1 and array2 (sorted, unique values in array1 not in array2):
[ 0 20 60]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [17]:


def find_set_xor(array1, array2):
    
    
    """
    Finds the set difference of two numpy arrays using built-in functions.

    Parameters:
        array1 (numpy.ndarray): The first array.
        array2 (numpy.ndarray): The second array.

    Returns:
        numpy.ndarray: A sorted array containing the unique values in array1 that are not in array2.
    """
    
    
    ex_or = np.setxor1d(array1, array2)
    return ex_or

def main():

    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])

    ex_or = find_set_xor(array1, array2)

    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print("Set Exclusive OR of array1 and array2 :")
    print(ex_or)

if __name__ == "__main__":
    main()



Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Set Exclusive OR of array1 and array2 :
[ 0 20 30 60]


15. Write a Python program to save a NumPy array to a text file.

In [18]:


def save_array_to_text_file(array, filename):
    """
    Saves a NumPy array to a text file.

    Parameters:
        array (numpy.ndarray): The NumPy array to save.
        filename (str): The name of the file to save the array to.
    """
    np.savetxt(filename, array, fmt='%d')
    print(f"Array saved to {filename}")
   
   

def main():

    array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


    filename = "output.txt"

   
    save_array_to_text_file(array, filename)
    

if __name__ == "__main__":
    main()
open('output.txt', mode = 'r',encoding='utf-8')

Array saved to output.txt


<_io.TextIOWrapper name='output.txt' mode='r' encoding='utf-8'>

16. Write a Python program to create a contiguous flattened array.

In [19]:

def create_flattened_array(array):
    
    
    """
    Creates a contiguous flattened array from a 2D NumPy array.

    Parameters:
        array (numpy.ndarray): The 2D NumPy array to flatten.
    
    Returns:
        numpy.ndarray: The flattened array.
    """
    
    
    return array.flatten()



def main():

    
    original_array = np.array([[10, 20, 30], [20, 40, 50]])
    print("Original array:")
    print(original_array)

    flattened_array = create_flattened_array(original_array)
    print("New flattened array:")
    print(flattened_array)

if __name__ == "__main__":
    main()


Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.


In [20]:


def force_change_data_type(array, new_type):
    
    
    """
    Forcefully changes the data type of each element in a NumPy array.

    Parameters:
        array (numpy.ndarray): The original NumPy array.
        new_type (type): The new data type for the array elements.
    
    Returns:
        numpy.ndarray: The array with elements cast to the new data type.
    """
    
    
    new_array = np.empty(array.shape, dtype=new_type)
    
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            new_array[i, j] = new_type(array[i, j])
    
    return new_array



def main():

    original_array = np.array([[2, 4, 6], [6, 8, 10]])
    print("Original array:")
    print(original_array)
    
    print("Data type of the array x is:", original_array.dtype)
    
    new_type = np.float64
    new_array = force_change_data_type(original_array, new_type)
    
    print("New Type:", new_type)
    print(new_array)

if __name__ == "__main__":
    main()


Original array:
[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type: <class 'numpy.float64'>
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [21]:

def create_3d_diagonal_array(shape):
    
    
    """
    description : 
        Creates a 3-D array with ones on the diagonal and zeros elsewhere.

    Parameters:
        shape (tuple): The shape of the 3-D array. Must be a tuple of three integers (depth, rows, columns).
    
    Returns:
        numpy.ndarray: The 3-D array with ones on the diagonal and zeros elsewhere.
    """
    depth, rows, cols = shape
    array = np.zeros((depth, rows, cols), dtype=int)
    
    
    for d in range(min(depth, rows, cols)):
        array[d, d, d] = 1
    
    return array

def main():
  
    shape = (4, 4, 4)  
    

    diagonal_array = create_3d_diagonal_array(shape)
    
    
    print("3-D Array with ones on the diagonal and zeros elsewhere:")
    print(diagonal_array)

if __name__ == "__main__":
    main()


3-D Array with ones on the diagonal and zeros elsewhere:
[[[1 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 1 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 1 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [22]:

def create_triangular_array(rows):
    
    
    """
    Creates a 2-D array with an increasing number of ones in each row, forming a triangular shape.

    Parameters:
        rows (int): The number of rows in the array.
    
    Returns:
        numpy.ndarray: The 2-D array with a triangular pattern of ones.
    """
    
    
    array = np.zeros((rows, rows), dtype=float)
    
    for i in range(rows):
        array[i, :i+1] = 1
    
    return array

def main():

    rows = 4 
    
    triangular_array = create_triangular_array(rows)
    
    print("2-D Array with a triangular pattern of ones:")
    print(triangular_array)

if __name__ == "__main__":
    main()



2-D Array with a triangular pattern of ones:
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.


In [23]:

def concatenate_arrays(array1, array2):
    
    
    """
    Concatenates two 2-D arrays horizontally (along columns).

    Parameters:
        array1 (numpy.ndarray): The first 2-D array.
        array2 (numpy.ndarray): The second 2-D array to concatenate with the first one.
    
    Returns:
        numpy.ndarray: The concatenated 2-D array.
    """
    
    
    return np.concatenate((array1, array2), axis=1)

def main():
  
    array1 = np.array([[0, 1, 3], [5, 7, 9]])
    array2 = np.array([[0, 2, 4], [6, 8, 10]])
    
    result = concatenate_arrays(array1, array2)
    
    print("Concatenated 2-D Array:")
    print(result)

if __name__ == "__main__":
    main()


Concatenated 2-D Array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).

In [24]:


def make_array_read_only_and_test():
    
    
    """
    Description:
        Creates a NumPy array with 10 elements, sets it to read-only, and attempts to modify it.
    
    Parameters:
        None
    
    Returns:
        None
    """
    
    
    x = np.zeros(10)
    
    x.flags.writeable = False


    
    print("Try to change the value of the first element:")
    
    try:
        x[0] = 1  
    except ValueError as e:
        print(f"Error: {e}")



def main():

    make_array_read_only_and_test()

if __name__ == "__main__":
    main()


Try to change the value of the first element:
Error: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.

In [25]:

def create_and_transform_array():
    
    
    """
    Description:
        Creates a list of integers from 1 to 12, converts it to a NumPy array, multiplies the array by 3,
        reshapes it into a 3x4 array, and prints the result.
    
    Parameters:
        None
    
    Returns:
        None
    """
    
    
    mylist = [i for i in range(1, 13)]
    
    array_2d = np.array(mylist)
    
    multiplied_array = array_2d * 3
    
    reshaped_array = multiplied_array.reshape(3, 4)
    
    print("Reshaped Array:")
    print(reshaped_array)



def main():

    create_and_transform_array()

if __name__ == "__main__":
    main()


Reshaped Array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]


23. Write a Python program to convert a NumPy array into Python list structure.

In [26]:

def convert_array_to_list(array):
    
    
    """
    Description:
        Converts a NumPy array to a Python list structure.
    
    Parameters:
        array (np.ndarray): The NumPy array to be converted.
    
    Returns:
        list: The converted Python list.
    """
    
    
    return array.tolist()


def main():

    array = np.array([[0, 1], [2, 3], [4, 5]])
    
    print("Original array elements:")
    print(array)
    
    list_structure = convert_array_to_list(array)
    
    print("Array to list:")
    print(list_structure)

if __name__ == "__main__":
    main()


Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.

In [27]:


def print_array_with_precision(array, precision):
    
    
    """
    Description:
        Prints the NumPy array values with a specified precision using string formatting.
    
    Parameters:
        array (np.ndarray): The NumPy array to print.
        precision (int): The number of decimal places to display.
    
    Returns:
        None
    """
    
    
    formatted_array = [f"{value:.{precision}f}" for value in array]
    
    print(formatted_array)



def main():

    array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 
                      0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
    
    print("Original array elements:")
    print(array)
    
    print("Print array values with precision 3:")
    print_array_with_precision(array, 3)

if __name__ == "__main__":
    main()


Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
['0.262', '0.528', '0.572', '0.593', '0.783', '0.697', '0.354', '0.995', '0.069', '0.547']


26.Write a Python program to how to add an extra column to an numpy array.

In [28]:


def add_column_to_array(array, new_column):
    
    """
    
    Description : 
        Adds an extra column to a NumPy array using numpy.append.

    Parameters:
        array (numpy.ndarray): The original 2D array to which the column will be added.
        new_column (numpy.ndarray): The new column to be added.

    Returns:
        numpy.ndarray: The array with the new column added.
        
        
    """
    new_column = new_column.reshape(-1, 1)
    
    updated_array = np.append(array, new_column, axis=1)
    
    return updated_array



def main():
    original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print("Original array:")
    print(original_array)
    
    new_column = np.array([10, 11, 12])
    
    updated_array = add_column_to_array(original_array, new_column)
    
    print("Array after adding the new column:")
    print(updated_array)

if __name__ == "__main__":
    main()

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding the new column:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


27. Write a Python program to remove specific elements in a numpy array.

In [29]:


def find_common_values(array1, array2):
    
    
    """
    Finds common values between two numpy arrays.

    Parameters:
        array1 (numpy.ndarray): The first array.
        array2 (numpy.ndarray): The second array.

    Returns:
        numpy.ndarray: An array containing the common values.
    """
    
    
    common_values = []
    for value in array1:
        if value in array2 and value not in common_values:
            common_values.append(value)
    return np.array(common_values)



def main():

    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])

    
    common_values = find_common_values(array1, array2)

    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print("Common values between two arrays:")
    print(common_values)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]
